catenax-ng/tx-managed-service-orchestrator

src/main/java/org/eclipse/tractusx/autosetup/exception/GlobalDefaultExceptionHandler.java, src/main/java/org/eclipse/tractusx/autosetup/manager/AutoSetupTriggerManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/CertificateManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/InputConfigurationManager.java, src/main/java/org/eclipse/tractusx/autosetup/model/Customer.java, src/main/java/org/eclipse/tractusx/autosetup/repository/AutoSetupTriggerEntryRepository.java, src/main/java/org/eclipse/tractusx/autosetup/service/AutoSetupOrchitestratorService.java
- Organisation name with more special c support for validation - https://jira.catena-x.net/browse/CPLP-2071
- add serviceId in auto setup duplication check
=> Organisation name with more special character support 

pom.xml
- update tomcat
- update key cloak version
- update spring security
=> update tomcat, spring security version

pom.xml, src/main/java/org/eclipse/tractusx/autosetup/service/AutoSetupOrchitestratorService.java
- Hot fix of Multi requesting of Managed SDE
- fix bouncy castle occure because of keycloak upgrade from 19 to 20
=> Hot fix of Multi requesting of Managed SDE

DEPENDENCIES
=> Update dependecies file

src/main/java/org/eclipse/tractusx/autosetup/constant/DAPsConfigurationProperty.java, src/main/java/org/eclipse/tractusx/autosetup/constant/SDEConfigurationProperty.java, src/main/java/org/eclipse/tractusx/autosetup/factory/builder/AppConfigurationBuilder.java, src/main/java/org/eclipse/tractusx/autosetup/manager/ConnectorCommonUtilityManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/DFTBackendManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/EDCControlplaneManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/TractusConnectorManager.java, src/main/java/org/eclipse/tractusx/autosetup/service/DFTAppWorkFlow.java, src/main/resources/flyway/V1__auto-setup-table.sql, src/test/java/org/eclipse/tractusx/autosetup/manager/DFTBackendManagerTest.java, src/test/java/org/eclipse/tractusx/autosetup/manager/EDCControlplaneManagerTest.java
- sonar code duplication issue fix, refactor code
=> fix sonar code duplication issue

src/main/java/org/eclipse/tractusx/autosetup/manager/DFTBackendManager.java, src/main/resources/flyway/V1__auto-setup-table.sql
change for sde backend postgres chart
=> change for sde backend postgres chart

src/test/java/org/eclipse/tractusx/autosetup/manager/DFTBackendManagerTest.java, src/test/resources/application-test.properties
=> test execution fix

.github/workflows/build.yaml, pom.xml, src/main/java/org/eclipse/tractusx/autosetup/manager/TestConnectorServiceManager.java, src/main/java/org/eclipse/tractusx/autosetup/testservice/proxy/ConnectorTestRequest.java, src/main/java/org/eclipse/tractusx/autosetup/testservice/proxy/ConnectorTestServiceProxy.java, src/main/java/org/eclipse/tractusx/autosetup/testservice/proxy/ConnectorTestServiceResponse.java
- add missing copyright header
=> add missing copyright header

src/main/java/org/eclipse/tractusx/autosetup/manager/TractusConnectorManager.java, src/main/java/org/eclipse/tractusx/autosetup/service/EDCConnectorWorkFlow.java, src/main/resources/flyway/V4__rename-tractus-connector.sql
- rename tx connector app name because ingress access issue
=> rename tx connector app name because ingress access issue

DEPENDENCIES, pom.xml
- Veracode spring expression issue fix
=> Veracode spring expression issue fix

pom.xml
=> Veracode library issue fix

pom.xml
- Veracode issue security web fix
=> Veracode issue security web fix

DEPENDENCIES, pom.xml
- Trivy fix and DEPENDENCIES file update
=> Trivy fix and DEPENDENCIES file update

CHANGELOG.md, DEPENDENCIES
- Update Spring boot version
- please merge 1st PR https://github.com/catenax-ng/tx-managed-service-orchestrator/pull/90
=> Fix: Upgrade springboot 3.1

CHANGELOG.md, README.md, charts/orchestrator/Chart.yaml, charts/orchestrator/README.md, pom.xml, src/main/java/org/eclipse/tractusx/autosetup/manager/AppDeleteManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/CertificateManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/ConnectorRegistrationManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/DTRegistryManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/PortalIntegrationManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/SDEManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/TestConnectorServiceManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/TractusConnectorManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/VaultManager.java
- improvement in portal feign client error logging
=> improvement in portal feign client error logging

CHANGELOG.md, README.md, charts/orchestrator/Chart.yaml, charts/orchestrator/README.md, pom.xml, src/main/java/org/eclipse/tractusx/autosetup/manager/SDEManager.java, src/main/java/org/eclipse/tractusx/autosetup/service/DTAppWorkFlow.java, src/main/java/org/eclipse/tractusx/autosetup/service/EDCConnectorWorkFlow.java, src/main/resources/application.properties
=> Skip portal step

CHANGELOG.md, README.md, charts/orchestrator/Chart.yaml, charts/orchestrator/README.md, pom.xml, src/main/java/org/eclipse/tractusx/autosetup/manager/PortalIntegrationManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/SDEManager.java, src/main/resources/templates/success_activate.html
- fix notification email sending issue
=> corrected email variable

.github/workflows/trivy.yml
Correct image name in trivy security scan
=> Correct image name in trivy security scan

.github/workflows/trivy.yml, CHANGELOG.md, README.md, charts/chart-testing-config.yaml, charts/orchestrator/Chart.yaml, charts/orchestrator/README.md, pom.xml, src/main/java/org/eclipse/tractusx/autosetup/config/EclipseLinkJpaConfiguration.java, src/main/java/org/eclipse/tractusx/autosetup/entity/AutoSetupTriggerEntry.java, src/main/java/org/eclipse/tractusx/autosetup/manager/ConnectorRegistrationManager.java, src/main/java/org/eclipse/tractusx/autosetup/service/AutoSetupOrchitestratorService.java, src/main/java/org/eclipse/tractusx/autosetup/service/DTAppWorkFlow.java, src/main/resources/templates/success.html
- Email notification only on successful component connectivity test
=> Sync email notification

CHANGELOG.md, README.md, charts/orchestrator/Chart.yaml, charts/orchestrator/README.md, charts/orchestrator/values.yaml, pom.xml, src/main/java/org/eclipse/tractusx/autosetup/constant/SDEConfigurationProperty.java, src/main/java/org/eclipse/tractusx/autosetup/manager/DTRegistryManager.java, src/main/resources/application.properties, src/main/resources/flyway/V8__update_app_version.sql, src/test/resources/application-test.properties
-  Support ddtr 3.2 for external subject id
=> Support ddtr 3.2

src/main/java/org/eclipse/tractusx/autosetup/apiproxy/EDCApiProxy.java, src/main/java/org/eclipse/tractusx/autosetup/apiproxy/EDCProxyService.java, src/main/java/org/eclipse/tractusx/autosetup/manager/DTRegistryManager.java, src/main/java/org/eclipse/tractusx/autosetup/manager/VaultManager.java, src/main/resources/edc-request-template/asset-request-filter.json, src/main/resources/edc-request-template/asset.json, src/main/resources/edc-request-template/contract-defination.json, src/main/resources/edc-request-template/policy.json
- Update dt asset creation for oauth secrete information
=> Update dt asset creation for oauth secrete information

src/main/java/org/eclipse/tractusx/autosetup/manager/DTRegistryManager.java, src/main/java/org/eclipse/tractusx/autosetup/service/AutoSetupOrchitestratorService.java, src/main/resources/application.properties, src/main/resources/flyway/V9__update_app_version.sql, src/main/resources/request-template/asset.json
- refactor DT registry local use
=> refactor DT registry local use

src/main/java/org/eclipse/tractusx/autosetup/manager/SDEManager.java, src/main/java/org/eclipse/tractusx/autosetup/service/DTAppWorkFlow.java
- Handle minio duplication
- Avoid auto setup failure in case DT asset creation failed
=> Handle minio user duplication

DEPENDENCIES, src/test/java/org/eclipse/tractusx/autosetup/manager/VaultManagerTest.java
- It will fix veracode workflow issue
=> Unit test case fixes

CHANGELOG.md, README.md, charts/orchestrator/Chart.lock, charts/orchestrator/Chart.yaml, charts/orchestrator/README.md, charts/orchestrator/values.yaml
- We are upgrading dependency postgresql DB
=> chore: Database upgrade
